### ISSUE TITLE
Referred your YouTube Video

### ISSUE THREAD

**Issue by devops-cloud-labs** [vaficionado/aws-clarity-ghapp#9]
https://www.youtube.com/watch?v=UixJCV_DkLg

I was looking for the scripts that have set the variables and environment variables.

We are setting up Azure DevOps pipelines to remote manage the Plan and Apply (instead of UI). We are using TFE.

Best Regards,
Sanjeev

**Comment by jonnyborbs** [comment]
Hi Sanjeev - check out https://github.com/vaficionado/tfe-workspace-setup and see if that helps

**Comment by devops-cloud-labs** [comment]
Thanks for your quick response. I later realised this was the most discussed question in Q&A.
